#pragma once

namespace BE_TextureEnums
{
	enum class Pixel_Sidescroller_City_Frames : unsigned
	{
		//
		//Abandoned City
		//

		ABANDONED_BUILDING_01,
		ABANDONED_BUILDING_02,
		ABANDONED_BUILDING_03,
		ABANDONED_BUILDING_04,
		ABANDONED_BUILDING_05,
		ABANDONED_BUILDING_06,
		ABANDONED_BUILDING_07,
		ABANDONED_BUILDING_08,

		ABANDONED_BUILDING_SILHOUETTE_BACK,
		ABANDONED_BUILDING_SILHOUETTE_FRONT,

		ABANDONED_TRAIN,
		ABANDONED_TRAIN_TRACKS,
		ABANDONED_TREES,

		ABANDONED_CLOUD_01,
		ABANDONED_CLOUD_02,
		ABANDONED_CLOUD_03,
		ABANDONED_CLOUD_04,
		ABANDONED_CLOUD_05,
		ABANDONED_CLOUD_06,
		ABANDONED_CLOUD_07,
		ABANDONED_CLOUD_08,

		ABANDONED_SMALL_BUILDING_01,
		ABANDONED_SMALL_BUILDING_02,
		ABANDONED_SMALL_BUILDING_03,
		ABANDONED_SMALL_BUILDING_04,
		ABANDONED_SMALL_BUILDING_04_A,
		ABANDONED_SMALL_BUILDING_05,
		ABANDONED_SMALL_BUILDING_06,
		ABANDONED_SMALL_BUILDING_07,
		ABANDONED_SMALL_BUILDING_07_A,
		ABANDONED_SMALL_BUILDING_08,
		ABANDONED_SMALL_BUILDING_09,

		ABANDONED_SMALL_TRAIN_TRACKS,
		ABANDONED_SMALL_TRAIN,
		ABANDONED_SMALL_TREES,

		//
		//Daytime City
		//

		DAYTIME_BACKGROUND,

		DAYTIME_BUILDING_02,
		DAYTIME_BUILDING_03,
		DAYTIME_BUILDING_04,
		DAYTIME_BUILDING_05,
		DAYTIME_BUILDING_06,
		DAYTIME_BUILDING_07,
		DAYTIME_BUILDING_08,

		DAYTIME_BUILDING_SILHOUETTE_BACK,
		DAYTIME_BUILDING_SILHOUETTE_FRONT,

		DAYTIME_CLOUD_01,
		DAYTIME_CLOUD_02,
		DAYTIME_CLOUD_03,
		DAYTIME_CLOUD_04,
		DAYTIME_CLOUD_05,
		DAYTIME_CLOUD_06,
		DAYTIME_CLOUD_07,
		DAYTIME_CLOUD_08,

		DAYTIME_TRAIN,
		DAYTIME_TRAIN_TRACKS,
		DAYTIME_TREES,

		DAYTIME_SMALL_BUILDING_01,
		DAYTIME_SMALL_BUILDING_02,
		DAYTIME_SMALL_BUILDING_03,
		DAYTIME_SMALL_BUILDING_04,
		DAYTIME_SMALL_BUILDING_05,
		DAYTIME_SMALL_BUILDING_06,
		DAYTIME_SMALL_BUILDING_07,
		DAYTIME_SMALL_BUILDING_08,
		DAYTIME_SMALL_BUILDING_09,

		DAYTIME_SMALL_TRAIN_TRACKS,
		DAYTIME_SMALL_TRAIN,
		DAYTIME_SMALL_TREES,

		//
		//Night City
		//

		NIGHT_BACKGROUND,

		NIGHT_BUILDING_01,
		NIGHT_BUILDING_02,
		NIGHT_BUILDING_03,
		NIGHT_BUILDING_04,
		NIGHT_BUILDING_05,
		NIGHT_BUILDING_06,
		NIGHT_BUILDING_07,
		NIGHT_BUILDING_08,

		NIGHT_BUILDING_SILHOUETTE_BACK,
		NIGHT_BUILDING_SILHOUETTE_FRONT,

		NIGHT_CLOUD_01,
		NIGHT_CLOUD_02,
		NIGHT_CLOUD_03,
		NIGHT_CLOUD_04,
		NIGHT_CLOUD_05,
		NIGHT_CLOUD_06,
		NIGHT_CLOUD_07,
		NIGHT_CLOUD_08,
		NIGHT_CLOUD_STRIPES,

		NIGHT_STARS_01,
		NIGHT_STARS_02,

		NIGHT_TRAIN,
		NIGHT_TRAIN_TRACKS,
		NIGHT_TREES,

		NIGHT_SMALL_BUILDING_01,
		NIGHT_SMALL_BUILDING_02,
		NIGHT_SMALL_BUILDING_03,
		NIGHT_SMALL_BUILDING_04,
		NIGHT_SMALL_BUILDING_05,
		NIGHT_SMALL_BUILDING_06,
		NIGHT_SMALL_BUILDING_07,
		NIGHT_SMALL_BUILDING_08,
		NIGHT_SMALL_BUILDING_09,

		NIGHT_SMALL_TRAIN_TRACKS,
		NIGHT_SMALL_TRAIN,
		NIGHT_SMALL_TREES,

		//
		//SnowRain
		//

		SNOWRAIN_BACKGROUND,

		SNOWRAIN_BUILDING_01,
		SNOWRAIN_BUILDING_02,
		SNOWRAIN_BUILDING_03,
		SNOWRAIN_BUILDING_04,
		SNOWRAIN_BUILDING_05,
		SNOWRAIN_BUILDING_06,
		SNOWRAIN_BUILDING_07,
		SNOWRAIN_BUILDING_08,

		SNOWRAIN_BUILDING_SILHOUETTE_BACK,
		SNOWRAIN_BUILDING_SILHOUETTE_FRONT,

		SNOWRAIN_CLOUD_BACK,
		SNOWRAIN_CLOUD_FRONT,
		SNOWRAIN_CLOUD_MID,
		SNOWRAIN_SNOW,

		SNOWRAIN_TRAIN,
		SNOWRAIN_TRAIN_TRACKS,
		SNOWRAIN_TREES,

		SNOWRAIN_SMALL_BUILDING_01,
		SNOWRAIN_SMALL_BUILDING_02,
		SNOWRAIN_SMALL_BUILDING_03,
		SNOWRAIN_SMALL_BUILDING_04,
		SNOWRAIN_SMALL_BUILDING_05,
		SNOWRAIN_SMALL_BUILDING_06,
		SNOWRAIN_SMALL_BUILDING_07,
		SNOWRAIN_SMALL_BUILDING_08,
		SNOWRAIN_SMALL_BUILDING_09,

		SNOWRAIN_SMALL_TRAIN_TRACKS,
		SNOWRAIN_SMALL_TRAIN,
		SNOWRAIN_SMALL_TREES,

		//
		//Sunset
		//

		SUNSET_SMALL_BUILDING_01,
		SUNSET_SMALL_BUILDING_02,
		SUNSET_SMALL_BUILDING_03,
		SUNSET_SMALL_BUILDING_04,
		SUNSET_SMALL_BUILDING_05,
		SUNSET_SMALL_BUILDING_06,
		SUNSET_SMALL_BUILDING_07,
		SUNSET_SMALL_BUILDING_08,
		SUNSET_SMALL_BUILDING_09,

		SUNSET_TRAIN_TRACKS,
		SUNSET_TRAIN,
		SUNSET_TREES,

		SUNSET_BACKGROUND,

		SUNSET_BUILDING_01,
		SUNSET_BUILDING_02,
		SUNSET_BUILDING_03,
		SUNSET_BUILDING_04,
		SUNSET_BUILDING_05,
		SUNSET_BUILDING_06,
		SUNSET_BUILDING_07,
		SUNSET_BUILDING_08,

		SUNSET_BUILDING_SILHOUETTE_BACK,
		SUNSET_BUILDING_SILHOUETTE_FRONT,

		SUNSET_CLOUD_01,
		SUNSET_CLOUD_02,
		SUNSET_CLOUD_03,
		SUNSET_CLOUD_04,
		SUNSET_CLOUD_05,
		SUNSET_CLOUD_06,
		SUNSET_CLOUD_07,
		SUNSET_CLOUD_08,
		SUNSET_CLOUD_STRIPES,
		SUNSET_SUN,

		SUNSET_SMALL_TRAIN,
		SUNSET_SMALL_TRAIN_TRACKS,
		SUNSET_SMALL_TREES,

		COUNT
	};
	typedef Pixel_Sidescroller_City_Frames PSC_Frames;
}